apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodchip.fullname" . }}
  labels:
    {{- include "woodchip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: backend
      protocol: TCP
      name: backend
    - port: 8000
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "woodchip.selectorLabels" . | nindent 4 }}
