name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      # Step 3: Lint the Helm chart
      # - name: Lint Helm Chart
      #   run: helm lint ./charts/woodchip

      # Step 4: Package the Helm chart
      - name: Package Helm Chart
        run: helm package ./charts/woodchip --destination ./dist

      # Step 5: Generate the Helm repository index
      - name: Generate Helm Repository Index
        run: |
          helm repo index ./dist --url https://amaning1.github.io/helm

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
